# 博客配置 | Blog Configuration
# keywords:
author: mews-base
# description: 

# 如需修改icon,请替换 source/images/favicon.ico 文件
# If you want to change the icon, please replace the source/images/favicon.ico file
avatar: /images/favicon.ico
copyright: 2025

# 个人信息 | Personal Information
name: mews

# 社交账号 | Social Account
github: https://github.com/mews-iidx
mail: mailto:mews@mews-base.com
#linkedin: https://linkedin.com/in/xxx
# QQ: http://sighttp.qq.com/authd?IDKEY=xxx

# TODO：适配更多的社交账号
# TODO: Add more social accounts
